UPDATE_TASK_SCHEMA = {
    "title": "Controller input schema for updating a task",
    "description": "Schema for validating input data when updating a task in Saviia",
    "type": "object",
    "properties": {
        "tid": {"type": "string"},
        "title": {"type": "string"},
        "description": {"type": "string"},
        "deadline": {
            "type": "string",
            "format": "date-time",
        },
        "creation": {
            "type": "string",
            "format": "date-time",
        },
        "execution": {
            "type": "string",
            "format": "date-time",
        },
        "priority": {
            "type": "integer",
            "minimum": 1,
            "maximum": 4,
        },
        "assignee": {"type": "string"},
        "assignee_email": {"type": "string", "format": "email"},
        "assignee_discord_username": {"type": "string"},
        "category": {"type": "string"},
        "periodicity": {"type": "string"},
        "bot_token": {"type": "string"},
        "completed": {"type": "boolean"},
        "task_channel_id": {"type": "string"},
    },
    "required": [
        "bot_token",
        "tid",
        "title",
        "deadline",
        "creation",
        "execution",
        "priority",
        "assignee",
        "assignee_email",
        "assignee_discord_username",
        "category",
        "description",
        "completed",
        "task_channel_id",
    ],
    "additionalProperties": False,
}
