GET_THIES_DATA_SCHEMA = {
    "title": "Controller input schema for retrieving THIES data",
    "description": "Schema for validating input data when getting THIES synchronization status.",
    "type": "object",
    "properties": {
        "sharepoint_client_id": {"type": "string"},
        "sharepoint_client_secret": {"type": "string"},
        "sharepoint_tenant_id": {"type": "string"},
        "sharepoint_tenant_name": {"type": "string"},
        "sharepoint_site_name": {"type": "string"},
        "local_backup_path": {"type": "string"},
        "sharepoint_destination_path": {"type": "string"},
        "ftp_host": {"type": "string"},
        "ftp_port": {"type": "integer"},
        "ftp_user": {"type": "string"},
        "ftp_password": {"type": "string"},
    },
    "required": [
        "sharepoint_client_id",
        "sharepoint_client_secret",
        "sharepoint_tenant_id",
        "sharepoint_tenant_name",
        "sharepoint_site_name",
        "local_backup_path",
        "sharepoint_destination_path",
        "ftp_host",
        "ftp_port",
        "ftp_user",
        "ftp_password",
    ],
    "additionalProperties": False,
}
