POST_THIES_DATA_SCHEMA = {
    "title": "Controller input schema for posting THIES data",
    "description": "Schema for validating input data when creating THIES backups and SharePoint uploads.",
    "type": "object",
    "properties": {
        "sharepoint_client_id": {"type": "string"},
        "sharepoint_client_secret": {"type": "string"},
        "sharepoint_tenant_id": {"type": "string"},
        "sharepoint_tenant_name": {"type": "string"},
        "sharepoint_site_name": {"type": "string"},
        "local_backup_path": {"type": "string"},
        "ftp_host": {"type": "string"},
        "ftp_port": {"type": "integer"},
        "ftp_user": {"type": "string"},
        "ftp_password": {"type": "string"},
        "need_to_sync": {"type": "boolean"},
        "need_to_backup": {"type": "boolean"},
        "sharepoint_destination_path": {"type": "string"},
        "ftp_server_folders_path": {
            "type": "array",
            "items": {"type": "string"},
            "minItems": 2,
            "maxItems": 2,
            "uniqueItems": True,
        },
        "local_backup_source_path": {"type": "string"},
    },
    "required": [
        "sharepoint_client_id",
        "sharepoint_client_secret",
        "sharepoint_tenant_id",
        "sharepoint_tenant_name",
        "sharepoint_site_name",
        "local_backup_path",
        "ftp_host",
        "ftp_port",
        "ftp_user",
        "ftp_password",
        "need_to_sync",
        "need_to_backup",
        "sharepoint_destination_path",
        "ftp_server_folders_path",
        "local_backup_source_path",
    ],
    "additionalProperties": False,
}
